import React from 'react';
import Nav from './components/Nav';
import Footer from './components/Footer';
import './globals.css';

export const metadata = {
  title: 'Docking app',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <>
      <Nav />
      {children}
      <Footer />
    </>
  );
};

export default RootLayout;
